app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_lucky_hi:
    path: /lucky/hi
    controller: App\Controller\LuckyController::hi

app_api_lucky_number:
    path: /api/lucky/number
    controller: App\Controller\LuckyControllerJson::jsonNumber

lucky_number:
    path: /lucky/number/twig
    controller: App\Controller\LuckyControllerTwig::number

home:
    path: /home
    controller: App\Controller\LuckyControllerTwig::home

about:
    path: /about
    controller: App\Controller\LuckyControllerTwig::about

me:
    path: /
    controller: App\Controller\LuckyControllerTwig::me

api_quote:
    path: /api/quote
    controller: App\Controller\LuckyControllerTwig::quote

report:
    path: /report
    controller: App\Controller\LuckyControllerTwig::report

card_init:
  path: '/card/init/{route}'
  controller: 'App\Controller\CardsController::init'

card:
  path: '/card'
  controller: 'App\Controller\CardsController::card'

deck:
  path: '/card/deck'
  controller: 'App\Controller\CardsController::deck'

deck_shuffle:
  path: '/card/deck/shuffle'
  controller: 'App\Controller\CardsController::deck_shuffle'

deck_draw:
  path: '/card/deck/draw'
  controller: 'App\Controller\CardsController::deck_draw'

deck_draw_num:
  path: '/card/deck/draw/{number<\d+>}'
  controller: 'App\Controller\CardsController::deck_draw_num'

api:
    path: /api
    controller: App\Controller\ApiController::api

deck_api:
    path: /api/deck
    controller: App\Controller\ApiController::apiDeck

deck_shuffle_api:
    path: /api/deck/shuffle
    controller: App\Controller\ApiController::apiShuffle

deck_draw_api:
  path: '/api/deck/draw'
  controller: App\Controller\ApiController::apiDraw

deck_draw_num_api:
    path: '/api/deck/draw/{number<\d+>}'
    controller: App\Controller\ApiController::apiDrawNum

deck_shuffle_jokers:
    path: /card/deck/shuffle/jokers
    controller: App\Controller\CardsController::deck_shuffle_jokers
