app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_lucky_hi:
    path: /lucky/hi
    controller: App\Controller\LuckyController::hi

app_api_lucky_number:
    path: /api/lucky/number
    controller: App\Controller\LuckyControllerJson::jsonNumber

lucky_number:
    path: /lucky/number/twig
    controller: App\Controller\LuckyControllerTwig::number

home:
    path: /home
    controller: App\Controller\LuckyControllerTwig::home

about:
    path: /about
    controller: App\Controller\LuckyControllerTwig::about


